make `tox.ini` compatible with the upcoming `tox` version 4
plone/Products.isurlinportal pull request #7
Opened 2021-08-06 19:27 UTC by jugmac00

`tox4` will support inline comments (#), so they need to be escaped for the `sed` command

2021-08-06 19:27 UTC, mister-roboto commented
@jugmac00 thanks for creating this Pull Request and help improve Plone!

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass.

Whenever you feel that the pull request is ready to be tested, either start all jenkins jobs pull requests by yourself, or simply add a comment in this pull request stating:

```
@jenkins-plone-org please run jobs
```

With this simple comment all the jobs will be started automatically.

Happy hacking!

2021-08-06 19:27 UTC, jugmac00 commented
@jenkins-plone-org please run jobs

2021-08-06 19:43 UTC, jugmac00 commented
@jenkins-plone-org please run jobs

2021-08-09 09:34 UTC, mauritsvanrees requested changes
I confirm that the current `tox.ini` fails with `tox4`.
With your branch it still fails. If it runs on your machine, then the error could be specific to Mac:

```
sed: 1: "s\#test-5.x.cfg\#test-5 ...": substitute pattern can not be delimited by newline or backslash
```

I usually take a single slash as delimiter, as long as it does not conflict with the rest of the pattern, and then `tox4` works for me:

```
sed -ie "s/test-5.x.cfg/test-{env:PLONE_VERSION}.x.cfg/" {envdir}/buildout.cfg
```

Can you change that?

2021-08-09 09:36 UTC, mauritsvanrees commented
BTW, there is no need to run Jenkins for this PR. The `tox.ini` has no influence there.

2021-08-09 09:41 UTC, mauritsvanrees approved these changes

2021-08-09 09:42 UTC, mauritsvanrees commented
I had the change locally, so I have pushed it to your branch. Let's see if the actions pass, then we can merge.

2021-08-09 10:04 UTC, mauritsvanrees commented
Tests are green, I merge.

I will actually remove the news snippet, as it is an internal detail which does not need to end up in the changelog on PyPI.
I know that a check is done for this by `mr.roboto`, but we can ignore that.

2021-08-09 10:04 UTC, merged